### ISSUE TITLE
Security certificate expired - unable to download the app

### ISSUE THREAD

**Issue by mapperfr** [dustMason/op1.fun.app#1]
Hey,
Tried to send you a message through the operator-1.com message board but it's easier here :)
I can't access the app download section on op1.fun website. According to Firefox, the certificate has expired on June 27th. Is it possible to fix it?
Cheers!
Jeremy

**Comment by dustMason** [comment]
Sorry about that! I've updated the link on the home page to point directly to the github release download. Thanks for raising
